echo "We are trying this practical from linux EC2"
echo "We are from batch-25 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Git"
echo " This is 3rd Commit "
echo "This is new branch"
echo "This is INC BRANCH"